// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-8MLtnsrIXFiYC1xgYueyb6PjGCY_4ME',
    appId: '1:229362294983:web:850eb5ddd78b08c05adee2',
    messagingSenderId: '229362294983',
    projectId: 'avt-farmers',
    authDomain: 'avt-farmers.firebaseapp.com',
    storageBucket: 'avt-farmers.appspot.com',
    measurementId: 'G-R9DTTFMEJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_0VblZmCjcIg4kUhcopwGx9ZJCsSzOZ8',
    appId: '1:229362294983:android:11d3586316436b5e5adee2',
    messagingSenderId: '229362294983',
    projectId: 'avt-farmers',
    storageBucket: 'avt-farmers.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWubx-NI7yuIvMaqASmPrO-F0F6wKBzYo',
    appId: '1:229362294983:ios:d7acdc049385fea15adee2',
    messagingSenderId: '229362294983',
    projectId: 'avt-farmers',
    storageBucket: 'avt-farmers.appspot.com',
    iosBundleId: 'com.example.farmersDetailsGenerator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWubx-NI7yuIvMaqASmPrO-F0F6wKBzYo',
    appId: '1:229362294983:ios:d7acdc049385fea15adee2',
    messagingSenderId: '229362294983',
    projectId: 'avt-farmers',
    storageBucket: 'avt-farmers.appspot.com',
    iosBundleId: 'com.example.farmersDetailsGenerator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-8MLtnsrIXFiYC1xgYueyb6PjGCY_4ME',
    appId: '1:229362294983:web:5862da3087ddf5675adee2',
    messagingSenderId: '229362294983',
    projectId: 'avt-farmers',
    authDomain: 'avt-farmers.firebaseapp.com',
    storageBucket: 'avt-farmers.appspot.com',
    measurementId: 'G-P4MFHK57NV',
  );
}
